# Some of the number should be adjusted for your build due to different ports
# The code was also made in Microbit BBC Makecode environment (so no imports her)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 0)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 0)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 0)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 0)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 0)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 30)
Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 30)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO1)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO4)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO5)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO6)
Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO7)
def on_forever():
    if input.button_is_pressed(Button.A):
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 30)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 30)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 110)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 45)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 45)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 140)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 110)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 45)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 45)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 140)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 30)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 30)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO6)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO7)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 360)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 0)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO1)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 360)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 0)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 360)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 0)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 360)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 0)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO4)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 360)
        basic.pause(2000)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 0)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO5)
    elif input.button_is_pressed(Button.B):
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO1)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO4)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO5)
    elif input.button_is_pressed(Button.AB):
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 360)
        basic.pause(1000)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 110)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 45)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 45)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 140)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 110)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 45)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 45)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 140)
        basic.pause(500)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 30)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 30)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO6)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO7)
        basic.pause(700)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 0)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
        basic.pause(700)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 0)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
    else:
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO1, 0)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO2, 0)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO3, 0)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO4, 0)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO5, 0)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO6, 30)
        Kitronik_Robotics_Board.servo_write(Kitronik_Robotics_Board.Servos.SERVO7, 30)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO1)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO2)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO3)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO4)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO5)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO6)
        Kitronik_Robotics_Board.servo_stop(Kitronik_Robotics_Board.Servos.SERVO7)
basic.forever(on_forever)
